name: Publish Images S3

on:
  push:
    paths:
      - 'posts/**/images/*'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Images
        run: ./scripts/copy-images
      - name: Process Images
        run: cd scripts && npm i && cd .. && ./scripts/resize-images
        env:
          IMAGE_DIR: 'images'
      - name: Sync Images to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'images'
